language: scala

dist: trusty

scala:
- 2.10.6
- 2.11.8

jdk:
- oraclejdk8

env:
  matrix:
    secure: GgP10jdplUgaQG1C3TCUgVCXJhbj8zgc2kZ2MLFpgea/YtyrbXKRf3f8wg3rpHoT4pORhilwq56Ic6q1BG8GkAE4POfp5XIU8StNtPAs+kCUWfKJ1jf2gIdbbxVs0dME0FcfNH6ryx6aknR2yCkWX9Yx2A7toinV7QlbF9AOH2y5OQTrCegfqjEYR/1NU0HxMF0tSM9/KhjkQEBVinTn/WE3cqsB9Nw6U6Fo0sWT9oz63/YflxhA9x8ccrxC6799kydZHvvvVzr5ecWUqT3cVQ4g0/2iK1R8Ah7yTW3BaVmP5F4Ytt3T1wf+8iPRX8z6DVS8cYLm2jVUMiOsJ+RxYPOHce3dJ06w0VBuyX2Y0sVgGrANIwAkE1K3HghG5kJRfnyNIcJtG6FrILzuA/CvO4rn50qF7Tn66Jf78nRrVNinFV533FvzF/z8pKudIsuJH5uvhX8C4u6+/ELk7ShJVpzcCbEFEOVh/8pZT01VTxwnanhE6oFi9zfQ5VrhCmlSxC/z5DyzDu9SuTHTctkrY9GGWQZCnJPVhfoJrlEOAY5T3ihcVtOoceghSpAT0+PCYQ4nwfRDKCE5iQdWDYBHUoZalvkNB8iNqTA1PhdHndPoEXIR393T9LN8RbsGi+0jsiPqnlWfloYjfwbnIBg2K5EHrLrBtea33+i6QxrDk6E=
