# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "photos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"image" VARCHAR NOT NULL,"bytes" INTEGER NOT NULL,"created_at" TIMESTAMP NOT NULL);

# --- !Downs

drop table "photos";

